# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RongCloudDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RongCloudDemo
  pod 'RongCloudIM/IMKit', '~> 5.3.1' # 即时通讯基础 UI 组件

  pod 'SnapKit'
  pod 'NotificationToast'

end
